- defaultTab: nodes
  description: "Fetch the leads from xiti through an API"
  executionEnabled: true
  group: TEST
  loglevel: INFO
  name: api_leads
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: "1"
    filter: dockerhost
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        docker run \
            -it \
            -e APP_XITI_SECRET=/keys/xiti_auth \
            -e APP_DB_SECRET=/keys/bnbiuser \
            -v /keys/xiti-secret:/keys/xiti_auth \
            -v /keys/bnbiuser:/keys/bnbiuser \
            containers.mpi-internal.com/yapo/data-api-leads:latest \
    keepgoing: false
    strategy: node-first

