qualityGate:
  coverage:
    enabled: false
  codeAnalysis:
    highsLimit: 0
    mediumsLimit: 0
    lowsLimit: 0
    spamThreshold: 10
    enabled: true
  JIRA:
    enabled: false
  reviewers:
    minRequiredApprovals: 1
