- defaultTab: nodes
  description: |-
    Etl that reads sellers that ended an ad so an survey would be send to their emails \
    https://github.mpi-internal.com/Yapo/data-traffic \
    sudo docker run --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
            -v /home/bnbiuser/secrets/zendesk_auth:/app/survey \
            -e APP_DB_SECRET=/app/db-secret \
            -e APP_SURVEY_SECRET=/app/survey \
            containers.mpi-internal.com/yapo/nps-sender:latest
  executionEnabled: true
  group: DOCKER/TRAFFIC
  loglevel: DEBUG
  name: ZENDESK - Surveypal nps sender
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: gp_data_analytics@yapo.cl
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
      plugin:
        configuration:
          slack_channel: ''
          webhook_base_url: https://hooks.slack.com/services
          webhook_token: T02U92SBN/B024F0M8EF5/6jLC6tWl4QNrYFpnyoLqqQZI
        type: SlackNotification
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '03'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/nps-sender:latest
        sudo docker run --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
            -v /home/bnbiuser/secrets/zendesk_auth:/app/survey \
            -e APP_DB_SECRET=/app/db-secret \
            -e APP_SURVEY_SECRET=/app/survey \
            containers.mpi-internal.com/yapo/nps-sender:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
