version: '2'
services:
  app:
    image: bi.etl.xiti.leads:1.0
    container_name: bi.etl.xiti.leads.container
    build: .
    networks:
      - regress
    ports:
      - "3000:3000"
networks:
  regress:
    external: true