version: '2'
services:
  api_leads:
    image: containers.mpi-internal.com/yapo/api-leads:latest
    container_name: api_leads
    environment:
      APP_XITI_SECRET: /keys/xiti_auth
      APP_DB_SECRET: /keys/bnbiuser
    volumes:
      - /keys/xiti_auth:/keys/xiti_auth
      - /keys/bnbiuser:/keys/bnbiuser
