version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_DW_SECRET: /app/dw-secret
    volumes:
      - ~/Projects/secrets/db-secret:/app/dw-secret
