version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_PULSE_SECRET: /app/pulse-secret
      APP_DB_SECRET: /app/db-secret
      APP_DW_SECRET: /app/dw-secret
    volumes:
      - ./secrets/blocket/secrets_blocket:/app/db-secret
      - ./secrets/dw/secrets_DW:/app/dw-secret
      - ./secrets/pulse/secrets_pulse:/app/pulse-secret
